export const ADD_ITEM = 'ADD_ITEM';
export const REMOVE_ITEM = 'REMOVE_ITEM';

export const SELL_DETAILS_REQUEST = 'SELL_DETAILS_REQUEST';
export const SELL_DETAILS_SUCCESS = 'SELL_DETAILS_SUCCESS';
export const SELL_DETAILS_FAIL = 'SELL_DETAILS_FAIL';
export const SELL_DETAILS_RESET = 'SELL_DETAILS_RESET';

export const SELL_CREATE_REQUEST = 'SELL_CREATE_REQUEST';
export const SELL_CREATE_SUCCESS = 'SELL_CREATE_SUCCESS';
export const SELL_CREATE_FAIL = 'SELL_CREATE_FAIL';
export const SELL_CREATE_RESET = 'SELL_CREATE_RESET';

export const SELL_LIST_REQUEST = 'SELL_LIST_REQUEST';
export const SELL_LIST_SUCCESS = 'SELL_LIST_SUCCESS';
export const SELL_LIST_FAIL = 'SELL_LIST_FAIL';
export const SELL_LIST_RESET = 'SELL_LIST_RESET';